name: Run on Specific Path Change

on:
  push:
    paths:
      - 'src/**'
      - 'README.md'
  pull_request:
    paths:
      - 'src/**'
      - 'README.md'

jobs:
  path-change-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print changed paths
        run: |
          echo "Triggered by a change in paths: ${{ github.event.head_commit.modified }}"
